version: "3"
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  tickets-service:
    build: ./tickets-service
    image: tickets-service:latest
    container_name: tickets-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tickets?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - MICROSERVICES_CINEMA-MICROSERVICE-URL=cinema-service:8060
    depends_on:
      - postgres

  films-service:
    build: ./films-service
    image: films-service:latest
    container_name: films-service
    ports:
      - "8070:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/films?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      - postgres

  cinema-service:
    build: ./cinema-service
    image: cinema-service:latest
    container_name: cinema-service
    ports:
      - "8060:8060"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cinema?currentSchema=public
      - SPRING_DATASOURCE_USERNAME=program
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - MICROSERVICES_FILM-MICROSERVICE-URL=films-service:8070
    depends_on:
      - postgres
      - films-service

volumes:
  db-data: